language: perl

perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"

notifications:
  email: true

matrix:
  # we don't need to continue any build when 1 test is failing.
  fast_finish: true

install:
  - rm -Rf cache

script:
  - perl -c uproxy

# Using the container-based infrastructure
sudo: false
